### ISSUE TITLE
Add support for chain `1` (testnet).

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/blue-app-eth#2]
According to SLIP44, all test networks are supposed to use a BIP44 path with the chain ID set to 1.  At the moment, the Ethereum Ledger app will reject anything that isn't chain `60` or `61`.

Add support for chain `1` as a valid BIP44 derivation path.

**Comment by MicahZoltu** [comment]
Fixed in https://github.com/LedgerHQ/blue-app-eth/commit/4a4dcdce9a469df7027b09c242adc2db5733800f, released on 2017-06-02.

**Comment by MicahZoltu** [comment]
Not yet released for the blue.

**Comment by btchip** [comment]
Should be done since 1.0.19
